### ISSUE TITLE
Create a Domain Model for the project

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#1]
- Make sure to avoid software terms and make it as understandable as possible for the average reader.

**Comment by Skellyboy38** [comment]
Simple example

![example](https://cloud.githubusercontent.com/assets/8304839/12199890/796e4ace-b5e9-11e5-918b-bc528a38a221.png)

**Comment by Skellyboy38** [comment]
![image](https://cloud.githubusercontent.com/assets/8304839/12200427/cd757ebe-b5ec-11e5-9afb-f93e12d25589.png)

**Comment by Skellyboy38** [comment]
**Ideas from tutorial:**

_The main boxes:_ Students, courses, Semester, tutorial, lab, calendar, the scheduler, List*

**Relations**

1) Student: Only one student registers. (To be continued)

**Comment by JoshuaChan-Fee** [comment]
Domain Model Draft (Simeon, Harrison, Joshua)
Student
- id 
- password
- username
- credits accumulated

Courses
- credits
- course name/number
- prerequisite

Course compartment
- type (tutorials, labs, lecture)
- staff
- time

Session
- semester (fall, winter, summer)

Scheduler

**Comment by Skellyboy38** [comment]
A draft of the domain model is now available in the drop box. Take a look and give feedback.

**Comment by ddayguerrero** [comment]
I have some proposed modifications for the domain model

**Comment by McGiver-** [comment]
Course compartment should have days of the week as well as time

**Comment by Skellyboy38** [comment]
Added the final domain model.
