### ISSUE TITLE
Create the purpose of the project

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#10]
- One paragraph should suffice.

**Comment by handriamanantena** [comment]
Here is the purpose:

The purpose of the scheduler is to make the registration process for University students as simple as possible. The system is designed to be as flexible as possible for students who may have certain preferences or missing prerequisites. The idea behind the scheduler, is to remove the burden of the complexity of registration. For most students, the difficulty of registration is trying to find a schedule which provides the best fit to their busy lives. Instead the scheduler will now try to optimize the student's preferences to generate the perfect schedule.
