### ISSUE TITLE
Design the back-end functionality 

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#12]
- Propose a model for python source files to follow (perhaps a UML)
- Give an outline of the purpose each class/script should fulfill

**Comment by Daviddube** [comment]
I'm trying to figure out what exactly we want the python to do. It'll definitely send the information to generate the pages; that's the views.py file. For the calendar/schedule creation, though, do we want to use javascript to have it generated directly on that page?

**Comment by Daviddube** [comment]
As for fetching the database, the database could simply be a .json file that views.py could read and pass onto the html/javascript.

**Comment by ddayguerrero** [comment]
^ assuming the information inside is static and won't need any queries

**Comment by Daviddube** [comment]
Isn't the database static? Not sure what you mean about queries. We should be able to get any necessary information from a .json file.

**Comment by Skellyboy38** [comment]
Yeah it will be completely static. All we need to do is fetch information and display it =) a .json should be fine in that case

**Comment by McGiver-** [comment]
Ya so flask is only for routing I guess the rest can be done and probably should be done in javascript

**Comment by McGiver-** [comment]
We spoke with derrel about the json file and it makes more sense, we still however should implement sql to save the chosen schedule for the user

**Comment by Skellyboy38** [comment]
This issue has been refactored into more precise, recent issues.
