### ISSUE TITLE
Design the database architecture

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#13]
- Decide on what tables and relations are required
- Give a visual representation/diagram

**Comment by JoshuaChan-Fee** [comment]
Here is the relationship diagram for the tables

![coursetablerelationship](https://cloud.githubusercontent.com/assets/16595437/12378356/e5729362-bd08-11e5-96fb-8d2cd5ad0b44.png)

**Comment by JoshuaChan-Fee** [comment]
Here are the descriptions of each table

![tabledescription](https://cloud.githubusercontent.com/assets/16595437/12378363/0c641c34-bd09-11e5-876c-56b46720dadf.png)

**Comment by ddayguerrero** [comment]
Nice, MS Access! Someone needs to look into SQL for python.

**Comment by JoshuaChan-Fee** [comment]
We don't need to use MS Access, it was just easier to show the relationship instead of drawing on paint.

**Comment by ddayguerrero** [comment]
Yeah, it's alright! The diagrams are clear! :+1:
