### ISSUE TITLE
#18 Define functional requirements 

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#18]
3.1 Functional Requirements

This section should describe the requirements that the software shall have. It should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. 

The overall functional requirements shall be presented graphically as a use case model.  
Each individual requirement shall be presented as a use case.  Also, each requirement should be rated in terms of difficulty and importance in order to provide useful discrimination factors for the project scoping presented in section 5.

**Comment by Skellyboy38** [comment]
You can find a model of what the functional requirements should look like on page 4 of example 1

**Comment by Daviddube** [comment]
![project use case diagram](https://cloud.githubusercontent.com/assets/9343325/12917677/c3cfd500-cf08-11e5-934f-0947c25cd2bc.png)

**Comment by Daviddube** [comment]
Completed 3.1, the use cases and use case diagram.
