### ISSUE TITLE
#21 Define resources

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#21]
1.  Resource Evaluation
   This section contains the resource evaluation for the project, expressed both in order to evaluate if resources are sufficient, scoping down if not, and also in order to allocate the resources in the subsequent project plan presented in section 6

4.1 Human Resources
Present here all your team members in terms of their capacities (strengths, knowledge, experience), as well as an evaluation of the time they can consecrate to the project over the semester,  and possible lack of availability during certain periods, which is important information to consider for concrete planning.

4.2  Technical Resources 
Present here the computer resources available for the project. That includes computers, software resources (tools, libraries, etc.) available on these computers

**Comment by Skellyboy38** [comment]
As far as I know everyone will be present all semester. There doesn't seem to be an example for you to follow for this one, so use your best judgment. 

edit: refer to page 35 of project example 1.

**Comment by Skellyboy38** [comment]
Known languages: Java, C++, C#, Python, HTML5, CSS3, JavaScript, PHP, MySQL, Oracle

**Comment by Daviddube** [comment]
Known languages: Java, C, C++, Python, HTML5, CSS, Javascript, PHP, Mysql, Ruby

**Comment by ddayguerrero** [comment]
Known languages: Java, C#, JavaScript, Ruby, Python, HTML5, CSS3, MySQL, PHP, VB.NET, Go

**Comment by JoshuaChan-Fee** [comment]
Known language: Java, VBA, HTML5, CSS, JavaScript, PHP, MySQL.

**Comment by Progaine** [comment]
Known languages: Java, HTML5, CSS3, JavaScript, PHP, SQL

**Comment by handriamanantena** [comment]
I'm still missing a couple of peoples languages.

**Comment by McGiver-** [comment]
C# java js html python css prolog bash

**Comment by cvesim** [comment]
Java, C#, Python, HTML, CSS

**Comment by handriamanantena** [comment]
Added software we were using as well as our programming setup. Also added everyone's programming knowledge in deliverable 1.
