### ISSUE TITLE
#22 Define the project scope

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#22]
1.  Scoping

With regard to the cost/time necessary to meet all the goal presented in section 3, and given the resources  available presented in section 4, give here the scope of the solution that you will implement in the project.

List all features/goals/qualities that will be left out because of lack of time/resources.

**Comment by Skellyboy38** [comment]
Read pages 14 and 15 of project example 1.

**Comment by JoshuaChan-Fee** [comment]
[4_Scoping.docx](https://github.com/ddayguerrero/soen341/files/121096/4_Scoping.docx)
