### ISSUE TITLE
#24 Define technologies in use

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#24]
6.2 Technologies in Use

List all the technologies that you plan to use in the project (e.g. programming languages, tools like compiler or IDE, libraries, etc. Give a brief rationale for the use of each technology, i.e. explanations describing why they are appropriate in the context of this project.

**Comment by Skellyboy38** [comment]
For 6.1 leave that for last.

**Comment by Skellyboy38** [comment]
There is no example in the sample project for technologies in use, but it should be straight forward. Aim for 1-2 pages explaining all the languages and frameworks we're using at a high level and why we're using them.

**Comment by PhilippeKuret** [comment]
[Deliverable 1 Technologies.docx](https://github.com/ddayguerrero/soen341/files/122604/Deliverable.1.Technologies.docx)

**Comment by PhilippeKuret** [comment]
If you think of other technologies, ill add them up
