### ISSUE TITLE
Design the student login page

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#3]
- Fill in the appropriate text/password fields
- Add a message that states the purpose of the webpage
- Give a set of instructions
- All to be done within home.html (already within the project folder)
- Only the skeleton needs to be done for now

**Comment by Skellyboy38** [comment]
The list of courses is already available on Moodle. I'll upload it to the drop box.

**Comment by Skellyboy38** [comment]
Woops closed the wrong issue.

**Comment by handriamanantena** [comment]
who is working on this right now? i saw that ali pushed a home page, but also that josh was assigned and then unassigned this issue.

**Comment by Progaine** [comment]
I'm thinking that we should add a pop-up window to handle logins and registrations, instead of a separate page.

**Comment by McGiver-** [comment]
Ali the pages you added are all already added in app and you arent following the proper flask layout.

**Comment by Skellyboy38** [comment]
Ali check out issue #28 , the problem is explained there.
