### ISSUE TITLE
#34 Design the dynamic design diagrams 

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#35]
From the word document:

"5 Validity and clarity of the dynamic design diagrams and contracts for each scenario. 

Compatibility of the scenarios with the components presented in section 2 and 3, as well as of the textual rationale."

@redfox300 and @Progaine will work together on this section.

Also, it relies heavily on sections 2 and 3 of the project (Robert and David).

**Comment by JoshuaChan-Fee** [comment]
it's on dropbox
