### ISSUE TITLE
#36 Revise cost estimation of each artifact

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#37]
From word document:

"6 Revised cost estimation of each individual artifact, validity of explanation of cost estimation, total cost estimate"

Refer back to deliverable 1 where cost was initially mentioned. Amend anything that now seems unrealistic or cannot be fulfilled by the end of the project. Explain your reasoning.

**Comment by JoshuaChan-Fee** [comment]
the document is on dropbox
