### ISSUE TITLE
Create a list of courses

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#4]
- This can be done in a simple text file
- Organize them by term (fall, winter, summer), then by days of the week, then by time
- Give them a name, section, and professor

**Comment by PhilippeKuret** [comment]
Are we supposed to get the list of courses from somewhere?  Or is it something we write ourselves?

**Comment by ddayguerrero** [comment]
@PhilippeKuret is right I think our sample data will come from specific resource files

**Comment by JoshuaChan-Fee** [comment]
The teacher said we can invent the data of the courses, it doesn't need to be the same as Concordia

**Comment by Skellyboy38** [comment]
@JoshuaChan-Fee Even if it is possible to invent them, it might be easier to simply fetch them from a resource file like Darrel mentioned. I have no idea how to do it yet, but it might be a lot easier lol

**Comment by cvesim** [comment]
So are we only getting data from "Engineering" programs?

**Comment by Skellyboy38** [comment]
first let's gauge how hard it will be to get courses just from engineering, and if it's not too much more work we can expand to all disciplines.

**Comment by Skellyboy38** [comment]
I'll assign this task to myself and look into how we're going to do this.

**Comment by Daviddube** [comment]
Sounds like we may even be able to simply have a file with all courses and their respective information...

**Comment by ddayguerrero** [comment]
Alright, but I think I recall seeing somewhere that a file will be given to us. I'll investigate that. If that's not the case, then I guess we will need to create the file ourselves. Perhaps a simple formatted text file, .json or even a .resx file

**Comment by Daviddube** [comment]
A .json file would be perfect for flask.

**Comment by Skellyboy38** [comment]
I found an excel file with a list of courses within the project folder on moodle. I uploaded it to the dropbox for everyone.

**Comment by McGiver-** [comment]
Ok so do we translate the courses from the excel file to an sql file or do we want to use an excel flask extension called Flask-Excel?(I think the sql file wiil be easier)

**Comment by Skellyboy38** [comment]
Yeah let's translate it to an sql file. I doubt it will take much time because copy pasting lines of code is a thing :P
