### ISSUE TITLE
#39 Create HTML form for logging in

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#40]
This is the first task of the list. 

We need an appropriate form for logging in that will enable the GET/POST requests to eventually log the user in if the information is correct. Doing the HTML code will suffice for this task.

Estimated time: 1 hour

Please be prompt; the deadline for the login page is February 25th by 11:59 pm.

**Comment by ddayguerrero** [comment]
I'll do it (see my message on Slack)

**Comment by Skellyboy38** [comment]
It looks great, thanks Darrel!
