### ISSUE TITLE
#41 Create the database and add a table for user login information

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#42]
First, the database needs to be created for the whole project.

Next, a table in which usernames and passwords are stored needs to be created.

SQLAlchemy is what we will use to link the database with the python source files, so take a look here before deciding on how to create the database:

http://flask-sqlalchemy.pocoo.org/2.1/quickstart/

According to the tutorial, a database.db object needs to be created, so that will be the purpose of this task. Just create the database.db object with the user login table included. 

@JoshuaChan-Fee , @ddayguerrero , and @PhilippeKuret 
You three will be in charge of this aspect of the project.

Please be prompt; the deadline for the login portion is February 25th by 11:59 pm.

**Comment by JoshuaChan-Fee** [comment]
Made the tables and the relationship between each tables and the file is on dropbox as well.

**Comment by Skellyboy38** [comment]
I don't see the database files. The database folder is empty?

**Comment by cvesim** [comment]
Sorry, I accidentally removed "databaseProject.py" from dropbox. It's back in the database folder.
I'm currently updating the "config.py" and the database module so that we can connect to the database.
