### ISSUE TITLE
#43 Validate the username and password field of the register.html page

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#44]
We need validation for user input when deciding on a username and password when registering for the website. This will involve a javascript file. Make sure that no special characters can be entered and add a minimum/maximum character limit. It is your choice on how you wish to display this information to the user (perhaps beside the text fields, or only when the user enters an invalid user/password).

This issue is DEPENDING ON #41 

Please be prompt; the deadline for the login aspect of the project is February 25th by 11:59 pm.

**Comment by ddayguerrero** [comment]
Two-level protection; these input fields will also need to be validated in the back-end.

**Comment by McGiver-** [comment]
Ok so ive been trying to get this dont for like 3 hours. I don't know why I can't get the regex to work properly.

**Comment by McGiver-** [comment]
Did someone play with the encoding ? Because it thinks I input special characters when im not.

**Comment by McGiver-** [comment]
Also doesn't register numbers.

**Comment by McGiver-** [comment]
ok so I made the charset utf 8 and now it works

**Comment by Skellyboy38** [comment]
George would you mind adding a message that appears beside the text field instead of an alert? They are kind of annoying lol.

**Comment by McGiver-** [comment]
Sure

**Comment by Skellyboy38** [comment]
This task is complete.
