### ISSUE TITLE
#45 Verify if login information is valid

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#46]
When a user attempts to log in, an error message needs to be displayed if the information is invalid. It is your choice on how to display this information. It can either appear below the username and password text fields, or as a prompt. 

Next, if a user successfully logs in, he/she should be redirected to a new page (which will be populated with information later on). 

This issue is DEPENDING ON #40 and #42 

Please be prompt; the deadline for the login aspect of the project is February 25th by 11:59 pm.

**Comment by Daviddube** [comment]
I have a good idea on how to do the verification right beside (or below) the username and password using javascript without the need of a prompt. I have a prototype already created. I only need to apply it to the form in issue #40.

**Comment by Daviddube** [comment]
If I'm not mistaken, this has been handled in **init**.py.
Nevermind, that's for the registration.

**Comment by handriamanantena** [comment]
ehh i added functionality to loging in and loging out. so you can't just /home on the url. you actually have to log in. i'm about to do a merge request.

**Comment by handriamanantena** [comment]
*pull request
