### ISSUE TITLE
Create a JSON script for students

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#5]
- This should be written in a text file with a .sql extension for now (to be integrated later)
- Create a table with the fields: ID, username, first name, last name
- ID will be a long while the rest are varchars
- The language will be MySql

**Comment by ddayguerrero** [comment]
also, ID is the primary key :+1:

**Comment by ddayguerrero** [comment]
@Daviddube or whoever knows Python, we need to figure out how to attach a db connection with our python codebase

**Comment by Skellyboy38** [comment]
This has been renamed from sql to json script to fit our specifications.

**Comment by Skellyboy38** [comment]
Using a JSON file will no longer be necessary as defined by the SQLAlchemy specifications.
