### ISSUE TITLE
Add sql alchemy to "requirements.txt"

### ISSUE THREAD

**Issue by cvesim** [ddayguerrero/soen341#50]

**Comment by Skellyboy38** [comment]
I don't see sql alchemy anywhere in the requirements. Has this been done already? Who's on this task?

**Comment by Skellyboy38** [comment]
Sorry Simeon I didn't realize you were working on this. I added them myself and pushed the changes.

**Comment by ddayguerrero** [comment]
Just a one-liner :+1:
