### ISSUE TITLE
Write a bash script to set up the virtual environment

### ISSUE THREAD

**Issue by cvesim** [ddayguerrero/soen341#54]

**Comment by cvesim** [comment]
Due to the way "virtualenv" is activated, we shall not use bash scripts.  
**Linux** 
`virtualenv .env && source .env/bin/activate && pip install -r requirements.txt`  
**Windows** 
It seems that system-wide requirements installation is inevitable. Best bet: set up a virtual machine with VirtualBox and use Linux.

**Comment by Skellyboy38** [comment]
The Linux command does appear to work in windows, however "bin" needs to be changed to "Scripts".

**Comment by Skellyboy38** [comment]
I'll close the issue since bash scripts will not be used. Thanks anyways Simeon.
