### ISSUE TITLE
Decide which modules/components will be used in the application

### ISSUE THREAD

**Issue by cvesim** [ddayguerrero/soen341#55]
Currently, we have the "authentication" module which follows an MVC structure and ensures appropriate login and registration. 
We need to discuss the creation of future modules under "app/{module_new-module}".

**Comment by ddayguerrero** [comment]
To be fair, modules should be expressed in terms of nouns (not verbs). This will help us define our actions with Flask later on.

e.g.
_app/calendar
app/class_

**Comment by Skellyboy38** [comment]
So far we have:

app/module_authentication/

and

app/module_schedule/

Would app/module_schedule/ need to be broken down further, or are 2 modules enough for the entire project?
