### ISSUE TITLE
Implement Home page UI, after student logs in

### ISSUE THREAD

**Issue by handriamanantena** [ddayguerrero/soen341#57]
Implement home page UI.

![image](https://cloud.githubusercontent.com/assets/12245215/13555636/20e075e8-e394-11e5-8a1b-e4e4aca3f12c.png)

**Comment by ddayguerrero** [comment]
Front-end almost done. kudos to @handriamanantena

**Comment by ddayguerrero** [comment]
Kind of done, will create more meaningful tasks for the schedule and course list.
