### ISSUE TITLE
Scrape Concordia's Software Enginerring course list data

### ISSUE THREAD

**Issue by ddayguerrero** [ddayguerrero/soen341#61]
Can be done with Python or JavaScript... 

https://campus.concordia.ca/psc/pscsprd/EMPLOYEE/HRMS/c/CU_EXT.CU_CLASS_SEARCH.GBL

**Comment by ddayguerrero** [comment]
This issue is only relevant if we cannot create our own course list data (need to confirm with teacher ASAP).

**Comment by cvesim** [comment]
I saved the html files for Fall2016, Summer2016 and Winter2016. I'm just parsing the html using "BeautifulSoup4". There is no need for any POST or GET request.

**Comment by cvesim** [comment]
Now, I need help to
1. Write the algorithm to parse the html (with BeautifulSoup and regex)
2. Formatting the data in the database
3. Determine the database models (Course, CourseRequirements, User...) and establish their relations
4. Fill the database with the scraped data
5. Create fictitious (sample) users with scheduling conflicts

Once this is done:
6. Write the algorithm to generate schedules.

**Comment by ddayguerrero** [comment]
Solved, we now need to parse the course information data into db and models.
