### ISSUE TITLE
Parse the entire course list data

### ISSUE THREAD

**Issue by ddayguerrero** [ddayguerrero/soen341#62]
either in XML or JSON

**Comment by Skellyboy38** [comment]
We have the csv files, but the database needs to be created no?

**Comment by cvesim** [comment]
That's what we are going to start doing tomorrow.

**Comment by ddayguerrero** [comment]
Almost done, just need to test.

**Comment by cvesim** [comment]
Current issues:
1. Link the technical, basic science and general electives to the student's sequence
2. Decide which types of requisites to consider (Prereqs, Coreqs, req1 OR req2 ) 
3. Decide how to handle/store more than one requisite per course
4. Fill partially instantiated models (such as Course which has undefined prereqs after parsing 
'courses.csv' ) 
5. Sum up all the script's functions into a single function 
6. Conditionally (depending on the existence of app.db) call the script's function when the app initializes
7. Verify the state of the database by either 'print <Model name here>.query.all()' or using a data frame

**Comment by ddayguerrero** [comment]
5 and 6 are completed
