### ISSUE TITLE
Define database/model diagram

### ISSUE THREAD

**Issue by JoshuaChan-Fee** [ddayguerrero/soen341#66]
Here is the database model

**Comment by JoshuaChan-Fee** [comment]
![database_model](https://cloud.githubusercontent.com/assets/16595437/13764226/cd126f52-ea23-11e5-84a2-6fe66a72a4eb.png)

**Comment by ddayguerrero** [comment]
+1

**Comment by Skellyboy38** [comment]
@Daviddube Here you go
