### ISSUE TITLE
Setup the team working environment

### ISSUE THREAD

**Issue by ddayguerrero** [ddayguerrero/soen341#7]
Before the real work begins, everyone needs to:
- Clone the GitHub repository
- Be familiar with basic Git commands
- Join the Slack chat room
- Join the team Dropbox
- Get a code editor / IDE
- Install Python 2.7 or 3.5 (Preferred)

**Comment by Skellyboy38** [comment]
Everything is up and running for me.

**Comment by McGiver-** [comment]
make sure that it is python 2.7, because they have different syntax.
