### ISSUE TITLE
Implement Add Course Pop up

### ISSUE THREAD

**Issue by handriamanantena** [ddayguerrero/soen341#73]
After the student clicks the Add Course button from the home page this pop up should appear. 
The schedule on the right should be the same template as the one on the home page. Jinja2 should be used to generate the same schedule which is on the home page see #57.

![image](https://cloud.githubusercontent.com/assets/12245215/13908330/99a1dd3a-eed6-11e5-9fbc-2d4cb8e3ddb3.png)

**Comment by ddayguerrero** [comment]
The modal can be implemented in a separate view, it does not need to be included with the "home" view.

**Comment by handriamanantena** [comment]
ok that works.

**Comment by handriamanantena** [comment]
lectures = [
    {
        'instructor': 'Don Davis',
        'id': '1',
        'semester_id': '1',
        'tutorials': [
            {'id': '2', 'startTime': '8:00','endTime': '9:00','dayOne': 'Monday', 'dayOne': 'Wednesday'},
            {'id': '2','startTime': '11:00','endTime': '12:00','dayOne': 'Monday', 'dayTwo': 'Wednesday'},
            {'id': '3', 'startTime': '8:00','endTime': '9:00','dayOne': 'Monday', 'dayOne': 'Wednesday'},
            {'id': '3','startTime': '11:00','endTime': '12:00','dayOne': 'Monday', 'dayTwo': 'Wednesday'}
        ],
        'labs': [
             {'id': '4', 'startTime': '10:00','endTime': '11:00','dayOne': 'Monday', 'dayOne': 'Wednesday'},
             {'id': 'None', 'startTime': 'None','endTime': 'None','dayOne': 'None', 'dayTwo': 'None'}
        ],
        'startTime': '18:00',
        'endTime': '21:00',
        'dayOne': 'Monday',
        'dayTwo': 'None'
    }
]

**Comment by Skellyboy38** [comment]
This is already completed.
