### ISSUE TITLE
3.2.2 Requirements testing

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#84]
A comment on testing in general:
## "Reproducibility of test cases. Exact description of test input data and expected results, and the procedure to convey all test cases. Description of the rationale for the derivation of each test case, e.g. equivalence partitioning analysis, branch coverage analysis, etc."

This section is on 8/50.

**Comment by Daviddube** [comment]
[Requirements Tests.docx](https://github.com/ddayguerrero/soen341/files/205043/Requirements.Tests.docx)
The requirements tests are complete.
