### ISSUE TITLE
Part 4.1 of deliverable 3

### ISSUE THREAD

**Issue by Skellyboy38** [ddayguerrero/soen341#86]
4.1: Clarity of instructions. Self-inclusion of the installation procedure, i.e. the installation does not necessitate the installation of external resources. This part is on 7/50.

**Comment by JoshuaChan-Fee** [comment]
@Daviddube 
![image](https://cloud.githubusercontent.com/assets/16595437/14268419/c8d7bace-faa8-11e5-893d-fefdbad5fdb7.png)
![image](https://cloud.githubusercontent.com/assets/16595437/14268423/cda7ee34-faa8-11e5-95e4-827babb484ea.png)
![image](https://cloud.githubusercontent.com/assets/16595437/14268430/df640f5e-faa8-11e5-80d2-8cdff4c5268d.png)
![image](https://cloud.githubusercontent.com/assets/16595437/14268432/e3d24f10-faa8-11e5-9ea4-cf0f9411ef9b.png)
![image](https://cloud.githubusercontent.com/assets/16595437/14268435/e5fed8bc-faa8-11e5-874b-801a292c3e21.png)

**Comment by Daviddube** [comment]
The python-equivalent screenshots have been taken.

**Comment by JoshuaChan-Fee** [comment]
you mean linux?

**Comment by Daviddube** [comment]
It's been a long weekend... yes, linux.

**Comment by JoshuaChan-Fee** [comment]
where did you post the images

**Comment by Daviddube** [comment]
They'll be up here tomorrow morning. Unless you want to work on them now?

**Comment by JoshuaChan-Fee** [comment]
umm I guess put them up tomorrow morning

**Comment by Daviddube** [comment]
[Linux.zip](https://github.com/ddayguerrero/soen341/files/204571/Linux.zip)
Here they are.
@ddayguerrero should linux have anything extra added?

**Comment by Skellyboy38** [comment]
Nicely done
